---
title: "Fraction of Optimal Codons x Fraction of Charged tRNAs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

setwd("/stor/work/Wilke/kelly/phage_simulation")

library(tidyverse)
library(ggplot2)
library(gtools)
library(stringr)
library(cowplot)
library(readxl)
SAVE_FIGS <- TRUE

cbPalette <- c("#CC79A7", "#56B4E9", "#E69F00", "#F0E442", "#0072B2", "#D55E00", "#009E73", "#999999")

# These are genes that are not included in the simulation and should be removed before comparing
# simulations with experimental data
IGNORE_GENES <- c("gene 10B",
                "possible gene 5.5-5.7",
                "gene 1.5",
                "gene 1.6",
                "gene 4.1",
                "gene 4B",
                "gene 0.6A",
                "gene 0.6B",
                "possible gene 0.6B",
                "gene 0.5",
                "gene 0.4")
```

```{r}
labels <- read_csv("output/id_map.csv") %>% filter(!is.na(gene_number))
load_sim <- function(paths) {
  data_list <- lapply(paths, function(path) {
    read_tsv(path) %>%
      mutate(file = path) %>%
      group_by(time) %>%
      nest() %>%
      mutate(data = purrr::map(data, ~full_join(labels, ., by = c("pinetree" = "species")))) %>%
      unnest() %>%
      mutate(time = round(time)) %>%
      mutate(protein = if_else(is.na(protein), 0, protein),
             transcript = if_else(is.na(transcript), 0, transcript)) %>%
      filter(
        !(pinetree %in% IGNORE_GENES),
        (!is.na(gene_number) | 
         str_detect(pinetree, "nonpref_charged|nonpref_uncharged|pref_charged|pref_uncharged"))
      )
  })
  bind_rows(data_list)
}

# Define the output directories and max time
output_dirs <- c("data/simulation/phage/codon_parallel_pref0.7_charge100",
                 "data/simulation/phage/codon_parallel_pref0.7_charge10",
                 "data/simulation/phage/codon_parallel_pref0.7_charge50")
max_time <- 825

# Extract pref_val and charge_val from the output directory string
pref_val <- as.numeric(str_extract(output_dirs[1], "(?<=pref)[0-9]\\.[0-9]"))

# Generate file paths for each charge rate
seeds <- 1:3
fop_proportions <- 1:9

all_data <- list()

for (output_dir in output_dirs) {
  charge_val <- as.numeric(str_extract(output_dir, "(?<=charge)[0-9]+"))
  
  file_paths <- expand.grid(seed = seeds, fop = fop_proportions) %>%
    mutate(file_name = sprintf("trna_phage_pref%.1f_%d_fop%d.tsv", pref_val, seed, fop)) %>%
    mutate(full_path = file.path(output_dir, file_name))

    # Check if the files exist
    file_exists <- file.exists(file_paths$full_path)

    # Filter out non-existing files
    existing_files <- file_paths$full_path[file_exists]
    
    if (length(existing_files) == 0) {
      warning(paste("No files found for charge", charge_val))
      next
    }
  
  # Load all simulations
  data <- load_sim(existing_files)
  
  # Add fop and charge columns
  data <- data %>%
    mutate(
      fop = as.numeric(str_extract(file, "(?<=fop)[0-9]+")),
      charge = charge_val
    )
  
  all_data[[as.character(charge_val)]] <- data
}

all_data <- bind_rows(all_data)

# Filter the data 
nonpref_charged_data <- all_data %>%
  filter(str_detect(pinetree, "nonpref_charged"))
nonpref_uncharged_data <- all_data %>%
  filter(str_detect(pinetree, "nonpref_uncharged"))

pref_charged_data <- all_data %>%
  filter(str_detect(pinetree, "pref_charged"))
pref_uncharged_data <- all_data %>%
  filter(str_detect(pinetree, "pref_uncharged"))

# Calculate average fraction of charged tRNAs for each proportion at max time
avg_nonpref_charged <- nonpref_charged_data %>%
  filter(time == max_time) %>%
  group_by(fop, charge) %>%
  summarize(avg_charged = mean(protein), .groups = "drop")

avg_nonpref_total <- nonpref_uncharged_data %>%
  filter(time == max_time) %>%
  group_by(fop, charge) %>%
  summarize(avg_total = mean(protein), .groups = "drop")

avg_pref_charged <- pref_charged_data %>%
  filter(time == max_time) %>%
  group_by(fop, charge) %>%
  summarize(avg_charged = mean(protein), .groups = "drop")

avg_pref_total <- pref_uncharged_data %>%
  filter(time == max_time) %>%
  group_by(fop, charge) %>%
  summarize(avg_total = mean(protein), .groups = "drop")

# Combine the data for plotting
avg_nonpref <- left_join(avg_nonpref_charged, avg_nonpref_total, by = c("fop", "charge")) %>%
  mutate(type = "Nonpref Charged")

avg_pref <- left_join(avg_pref_charged, avg_pref_total, by = c("fop", "charge")) %>%
  mutate(type = "Pref Charged")

avg_tRNAfractionCharged <- bind_rows(avg_nonpref, avg_pref)

# Create the plot
avg_plot <- ggplot(avg_tRNAfractionCharged, aes(x = fop, y = avg_charged / (avg_charged + avg_total), color = as.factor(charge), linetype = type)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(x = "Fraction of Optimal Codons", y = paste("Fraction of Charged tRNAs at", max_time, "s"), title = paste("Fraction of Charged tRNAs at", max_time, "s for Fractions of Optimal Codons [ tRNA pref proportion:", pref_val, "]")) +
  scale_x_continuous(breaks = seq(1, 9, by = 1), labels = seq(0.1, 0.9, by = 0.1)) +
  scale_color_manual(values = cbPalette) +
  scale_linetype_manual(values = c("dashed", "solid"))

if (SAVE_FIGS) {
  save_plot(sprintf("analysis/figures/fraction_codonsXtrnas_%ds_pref%.1f.pdf", max_time, pref_val), avg_plot, base_width = 12, base_height = 12)
}
```