---
title: "FOP of Each Gene"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

setwd("/stor/work/Wilke/kelly/phage_simulation")

library(tidyverse)
library(ggplot2)
library(gtools)
library(stringr)
library(cowplot)
library(readxl)
SAVE_FIGS <- TRUE

cbPalette <- c("#CC79A7", "#56B4E9", "#E69F00", "#F0E442", "#0072B2", "#D55E00", "#009E73", "#999999")

# These are genes that are not included in the simulation and should be removed before comparing
# simulations with experimental data
IGNORE_GENES <- c("gene 10B",
                "possible gene 5.5-5.7",
                "gene 1.5",
                "gene 1.6",
                "gene 4.1",
                "gene 4B",
                "gene 0.6A",
                "gene 0.6B",
                "possible gene 0.6B",
                "gene 0.5",
                "gene 0.4")
```

```{r}
id_map <- read_csv("output/id_map.csv") %>% filter(!is.na(gene_number), !(pinetree %in% IGNORE_GENES))
gene_labels <- unique(mixedsort(id_map$gene_number))

# Load the FOP scores and lengths
fops_lengths <- read_csv("src/python/models/trna_phage_model/fop_scores_and_lengths.csv") 

# Handle missing values
fops_lengths$fop_score[is.na(fops_lengths$fop_score)] <- 0

# Extract gene_number from gene_name
fops_lengths <- fops_lengths %>%
  mutate(gene_number = str_extract(gene_name, "(?<=gene )[\\d\\.A-Za-z]+"))

# Add class to fop_lengths from id_map
fops_lengths <- fops_lengths %>%
  left_join(id_map, by = c("gene_number" = "gene_number")) %>%
  filter(!is.na(class))
View(fops_lengths)
```

```{r}
barplot <- ggplot(fops_lengths, aes(x=factor(gene_number, levels = rev(gene_labels)), y=fop_score, fill=factor(class))) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = (match(c("3.8", "4.7", "6.5", "18.5"), rev(gene_labels))) - 0.5, 
             linetype="dashed", color = "gray40") +
  geom_vline(xintercept = (match(c("11"), rev(gene_labels))) - 0.5) +
  theme(legend.position = "none") +
  labs(x="Gene", y="Fraction of Optimal Codons", title = paste("Fraction of Optimal Codons by Gene")) +
  theme(axis.ticks.x=element_blank()) +
  scale_fill_manual(values=cbPalette) +
  coord_flip()

if (SAVE_FIGS) {
  save_plot("analysis/figures/fop_by_gene.pdf", barplot, base_width = 6, base_height = 6)
}
```