---
title: "TRNA Model Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#setwd("/stor/work/Wilke/kelly/phage_simulation")

library(tidyverse)
library(ggplot2)
library(gtools)
library(stringr)
library(cowplot)
library(readxl)
SAVE_FIGS <- TRUE

cbPalette <- c("#CC79A7", "#56B4E9", "#E69F00", "#F0E442", "#0072B2", "#D55E00", "#009E73", "#999999")

# These are genes that are not included in the simulation and should be removed before comparing
# simulations with experimental data
IGNORE_GENES <- c("gene 10B",
                "possible gene 5.5-5.7",
                "gene 1.5",
                "gene 1.6",
                "gene 4.1",
                "gene 4B",
                "gene 0.6A",
                "gene 0.6B",
                "possible gene 0.6B",
                "gene 0.5",
                "gene 0.4")
```

```{r}
id_map <- read_csv("output/id_map.csv") %>% filter(!is.na(gene_number), !(pinetree %in% IGNORE_GENES))
gene_labels <- unique(mixedsort(id_map$gene_number))
```

```{r}
labels <- read_csv("output/id_map.csv") %>% filter(!is.na(gene_number))
load_sim <- function(path) {
  read_tsv(path) %>% group_by(time) %>% nest() %>%
    mutate(data = purrr::map(data, ~left_join(labels, ., by = c("pinetree" = "species")))) %>%
    unnest() %>%
    mutate(time = round(time)) %>%
    mutate(protein = if_else(is.na(protein), 0, protein),
           transcript = if_else(is.na(transcript), 0, transcript)) %>%
    filter(!(pinetree %in% IGNORE_GENES), !is.na(gene_number))
}

# Define the output directory
output_dir <- "data/simulation/phage/trna_parallel_output"

# Generate file paths
pref_proportions <- seq(0.1, 1, by = 0.1)
seeds <- 1:3

file_paths <- expand.grid(pref = pref_proportions, seed = seeds) %>%
  mutate(file_name = sprintf("trna_phage_pref%.1f_%d.tsv", pref, seed)) %>%
  mutate(full_path = file.path(output_dir, file_name))

# Load all simulations
all_data <- load_sim(file_paths$full_path)

# Add proportion and seed columns
all_data <- all_data %>%
  mutate(
    proportion = as.numeric(str_extract(file, "(?<=pref)[0-9]\\.[0-9]")),
    seed = as.numeric(str_extract(file, "(?<=_)[0-9](?=\\.tsv)"))
  )

# Calculate average proteins for each proportion at 420 seconds
avg_proteins_420 <- all_data %>%
  filter(time == 420) %>%
  group_by(proportion, gene_number, class) %>%
  summarize(avg_protein = mean(protein), .groups = "drop")

# Create the plot
avg_plot_420 <- ggplot(avg_proteins_420, 
                   aes(x = factor(gene_number, gene_labels), 
                       y = avg_protein, 
                       fill = factor(class))) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = (match(c("3.8", "4.7", "6.5", "18.5"), gene_labels)) - 0.5, 
             linetype="dashed", color = "gray40") +
  geom_vline(xintercept = (match(c("11"), gene_labels)) - 0.5) +
  facet_wrap(~proportion, ncol = 2, scales = "free_y") +
  theme(legend.position = "bottom") +
  labs(x = "Gene", y = "Average Proteins at 420s", fill = "Class") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = cbPalette)

if (SAVE_FIGS) {
  save_plot("analysis/figures/trna_avg_proteins_by_proportion_420s.pdf", avg_plot_420, base_width = 12, base_height = 16)
}
```